# https://www.getzola.org/themes/adidoks/ for config options
# The URL the site will be built for
base_url = "https://jbales.dev"
title = "jbales.dev"
description = "This is a personal website of Joseph Bales, a developer located in Nashville, TN."

# The site theme to use.
theme = "adidoks"

# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to generate a feed file for the site
generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# When set to "true", the generated HTML files are minified.
minify_html = false

# Set HTML file language
language_code = "en-US"

# Set theme-color meta tag for Chrome browser
theme_color = "#5b825b"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Joseph Bales"
github = "https://github.com/josephbales"
email = "hello@jbales.dev"
title = "trying this okay"

# More about site's title
title_separator = "|"  # set as |, -, _, etc
title_addition = "Custom Documentation Theme"

# Set date format in blog publish metadata
timeformat = "%B %e, %Y" # e.g. June 14, 2021
timezone = "UTC"

[[extra.menu.main]]
name = "Blog"
section = "blog"
url = "/blog/"
weight = 10

[[extra.menu.main]]
name = "About"
section = "about"
url = "/about/"
weight = 20

[[extra.menu.main]]
name = "Contact"
section = "contact"
url = "/contact/"
weight = 30

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/josephbales"
post = ""
weight = 10

[[extra.menu.social]]
name = "Email"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M0,0V10H20V0ZM0,1 10,6 20,1" transform="translate(0,6)"/></svg>'
url = "mailto:hello@jbales.dev"
post = "hello@jbales.dev"
weight = 20

# Footer contents
[extra.footer]
info = 'Powered by <a href="https://www.getzola.org/">Zola</a> and <a href="https://github.com/aaranxu/adidoks">AdiDoks</a>'

[[extra.footer.nav]]
name = "Privacy"
url = "/privacy-policy/"
weight = 10