name: "Build and Deploy jbales.dev"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code repo
      uses: actions/checkout@v3
      with:
        submodules: true
        path: main
    - name: Checkout deployment repo
      uses: actions/checkout@v3
      with:
        repository: josephbales/jbales.dev
        token: ${{ secrets.JBALES_DEV_TOKEN }}
        path: deployment
    - run: |
        ls -al main
        ls -al deployment
        git version
        git log -p -1